apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-volume
  labels:
    {{- include "chatqna.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
